@SET JAVA_VERSION=8
@SET ANT_VERSION=1.10.x
@SET JAVA_HOME=C:\JDK\%JAVA_VERSION%
@SET ANT_HOME=C:\ant\%ANT_VERSION%
@echo === Java %JAVA_VERSION%, ant %ANT_VERSION% Command Prompt ===
@echo JAVA_HOME=%JAVA_HOME%
@echo ANT_HOME=%ANT_HOME%
