@SET JAVA_VERSION=17
@SET GRADLE_VERSION=9.x
@SET JAVA_HOME=C:\JDK\%JAVA_VERSION%
@SET GRADLE_HOME=C:\Gradle\%GRADLE_VERSION%
@echo === Java %JAVA_VERSION%, Gradle %GRADLE_VERSION% Command Prompt ===
@echo JAVA_HOME=%JAVA_HOME%
@echo GRADLE_HOME=%GRADLE_HOME%
