@SET JAVA_VERSION=17
@SET MAVEN_VERSION=3.9.x
@SET JAVA_HOME=C:\JDK\%JAVA_VERSION%
@SET MAVEN_HOME=C:\Maven\%MAVEN_VERSION%
@echo === Java %JAVA_VERSION%, Maven %MAVEN_VERSION% Command Prompt ===
@echo JAVA_HOME=%JAVA_HOME%
@echo MAVEN_HOME=%MAVEN_HOME%
