@SET CMAKE_VERSION=3.x
:: MinGW-w64는 무조건 최신 버전으로 사용하고 버전관리를 하지 않는다. 
:: 경로는 하나만 쓰지만, 경로를 결정하지 않는 버전만 명시해주자!
@SET MINGW_W64_VERSION=15.1.0-posix-ucrt
@SET LLVM_CLANG_VERSION=20.x
@SET NINJA_VERSION=1.13.0
@SET CMAKE_HOME=C:\CMake\%CMAKE_VERSION%
@SET MINGW_W64_HOME=C:\MinGW-w64
@SET LLVM_CLANG_HOME=C:\LLVM\%LLVM_CLANG_VERSION%
@SET NINJA_HOME=C:\Ninja\latest
@echo === CMake %CMAKE_VERSION%, MinGW-w64 %MINGW_W64_VERSION%, LLVM+CLang %LLVM_CLANG_VERSION%, Ninja %NINJA_VERSION% Command Prompt ===
@echo CMAKE_HOME=%CMAKE_HOME%
@echo MINGW_W64_HOME=%MINGW_W64_HOME%
@echo LLVM_CLANG_HOME=%LLVM_CLANG_HOME%
@echo NINJA_HOME=%NINJA_HOME%
