@SET JAVA_VERSION=17
@SET ANT_VERSION=1.10.x
@SET MAVEN_VERSION=3.9.x
@SET GRADLE_VERSION=9.x
@SET JAVA_HOME=C:\JDK\%JAVA_VERSION%
@SET ANT_HOME=C:\ant\%ANT_VERSION%
@SET MAVEN_HOME=C:\Maven\%MAVEN_VERSION%
@SET GRADLE_HOME=C:\Gradle\%GRADLE_VERSION%
@echo === Java %JAVA_VERSION%, ant %ANT_VERSION%, Maven %MAVEN_VERSION%, Gradle %GRADLE_VERSION% Command Prompt ===
@echo JAVA_HOME=%JAVA_HOME%
@echo ANT_HOME=%ANT_HOME%
@echo MAVEN_HOME=%MAVEN_HOME%
@echo GRADLE_HOME=%GRADLE_HOME%